### ISSUE TITLE
[Bug]: JetNews crashed when starting for CircularProgressIndicator

### ISSUE THREAD

**Issue by MoseDien** [android/compose-samples#1248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

JetNews

### What happened?

It keeps crash when starting JetNews.
The same issue with this https://stackoverflow.com/questions/77877363

### Relevant logcat output

```shell
01-25 17:16:41.124 11247 11247 E AndroidRuntime: FATAL EXCEPTION: main
01-25 17:16:41.124 11247 11247 E AndroidRuntime: Process: com.example.jetnews, PID: 11247
01-25 17:16:41.124 11247 11247 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method at(Ljava/lang/Object;I)Landroidx/compose/animation/core/KeyframesSpec$KeyframeEntity; in class Landroidx/compose/animation/core/KeyframesSpec$KeyframesSpecConfig; or its super classes (declaration of 'androidx.compose.animation.core.KeyframesSpec$KeyframesSpecConfig' appears in /data/app/~~R8dkSNtNMuC5ObxAU0i0sg==/com.example.jetnews-nsw2m-N5VrS5p5sJGOOSTw==/base.apk)
01-25 17:16:41.124 11247 11247 E AndroidRuntime: 	at androidx.compose.material3.ProgressIndicatorKt$CircularProgressIndicator$endAngle$1.invoke(ProgressIndicator.kt:371)
01-25 17:16:41.124 11247 11247 E AndroidRuntime: 	at androidx.compose.material3.ProgressIndicatorKt$CircularProgressIndicator$endAngle$1.invoke(ProgressIndicator.kt:369)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by logicgupta** [comment]
Please assign me
