### ISSUE TITLE
[Bug]: PlayerScreen doesn't render Previews in Iguana beta 2

### ISSUE THREAD

**Issue by JoseAlcerreca** [android/compose-samples#1253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Jetcaster

### What happened?

Studio shows "Render problem" with:
java.lang.NoSuchFieldError: consume_window_insets_tag
	at androidx.compose.foundation.layout.WindowInsetsHolder.<init>(WindowInsets.android.kt:492)

### Relevant logcat output

```shell
at androidx.compose.foundation.layout.WindowInsetsHolder.<init>(WindowInsets.android.kt)
	at androidx.compose.foundation.layout.WindowInsetsHolder$Companion.getOrCreateFor(WindowInsets.android.kt:648)
	at androidx.compose.foundation.layout.WindowInsetsHolder$Companion.current(WindowInsets.android.kt:629)
	at androidx.compose.foundation.layout.WindowInsetsPadding_androidKt$systemBarsPadding$$inlined$windowInsetsPadding$1.invoke(WindowInsetsPadding.android.kt:250)
	at androidx.compose.foundation.layout.WindowInsetsPadding_androidKt$systemBarsPadding$$inlined$windowInsetsPadding$1.invoke(WindowInsetsPadding.android.kt:249)
	at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt:270)
	at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt:265)
	at androidx.compose.ui.Modifier$Element.foldIn(Modifier.kt:136)
	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:396)
	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:396)
	at androidx.compose.ui.ComposedModifierKt.materializeModifier(ComposedModifier.kt:265)
	at androidx.compose.ui.layout.LayoutKt$materializerOf$1.invoke-Deg8D_g(Layout.kt:204)
	at androidx.compose.ui.layout.LayoutKt$materializerOf$1.invoke(Layout.kt:202)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at com.example.jetcaster.ui.player.PlayerScreenKt.PlayerContentRegular(PlayerScreen.kt:661)
	at com.example.jetcaster.ui.player.PlayerScreenKt.access$PlayerContentRegular(PlayerScreen.kt:1)
	at com.example.jetcaster.ui.player.PlayerScreenKt$PlayerContent$1.invoke(PlayerScreen.kt:206)
	at com.example.jetcaster.ui.player.PlayerScreenKt$PlayerContent$1.invoke(PlayerScreen.kt:147)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at com.example.jetcaster.ui.player.PlayerScreenKt$PlayerDynamicTheme$1.invoke(PlayerScreen.kt:572)
	at com.example.jetcaster.ui.player.PlayerScreenKt$PlayerDynamicTheme$1.invoke(PlayerScreen.kt:563)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.material.MaterialTheme_androidKt.PlatformMaterialTheme(MaterialTheme.android.kt:23)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:82)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1$1.invoke(MaterialTheme.kt:81)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
	at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:396)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:81)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:80)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:72)
	at com.example.jetcaster.util.DynamicThemingKt.DynamicThemePrimaryColorsFromImage(DynamicTheming.kt:73)
	at com.example.jetcaster.ui.player.PlayerScreenKt.PlayerDynamicTheme(PlayerScreen.kt:563)
	at com.example.jetcaster.ui.player.PlayerScreenKt.PlayerContent(PlayerScreen.kt:147)
	at com.example.jetcaster.ui.player.PlayerScreenKt$PlayerScreen$2.invoke(PlayerScreen.kt:132)
	at com.example.jetcaster.ui.player.PlayerScreenKt$PlayerScreen$2.invoke(PlayerScreen.kt:130)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:138)
	at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:118)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:115)
	at com.example.jetcaster.ui.player.PlayerScreenKt.PlayerScreen(PlayerScreen.kt:130)
	at com.example.jetcaster.ui.player.PlayerScreenKt.access$PlayerScreen(PlayerScreen.kt:1)
	at com.example.jetcaster.ui.player.ComposableSingletons$PlayerScreenKt$lambda-6$1.invoke(PlayerScreen.kt:615)
	at com.example.jetcaster.ui.player.ComposableSingletons$PlayerScreenKt$lambda-6$1.invoke(PlayerScreen.kt:614)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1$1$measurables$1.invoke(BoxWithConstraints.kt:69)
	at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1$1$measurables$1.invoke(BoxWithConstraints.kt:69)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:989)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(SubcomposeLayout.kt:476)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:90)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3302)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3235)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:723)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1071)
	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3599)
	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:631)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:617)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcomposeInto(SubcomposeLayout.kt:499)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:471)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:462)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:446)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:871)
	at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1$1.invoke-0kLqBqw(BoxWithConstraints.kt:69)
	at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1$1.invoke(BoxWithConstraints.kt:67)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:708)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:252)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:251)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:500)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:256)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:113)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1617)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:36)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:620)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(LayoutNodeLayoutDelegate.kt:596)
	at androidx.compose.ui.layout.RootMeasurePolicy.measure-3p2s80s(RootMeasurePolicy.kt:38)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:126)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:252)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:251)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:500)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:256)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:113)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1617)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:36)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:620)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:1145)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:354)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureOnly(MeasureAndLayoutDelegate.kt:562)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureOnly(MeasureAndLayoutDelegate.kt:407)
	at androidx.compose.ui.platform.AndroidComposeView.onMeasure_Original(AndroidComposeView.android.kt:1058)
	at androidx.compose.ui.platform.AndroidComposeView.onMeasure(AndroidComposeView.android.kt)
	at android.view.View.measure_Original(View.java:27122)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:27083)
	at androidx.compose.ui.platform.AbstractComposeView.internalOnMeasure$ui_release(ComposeView.android.kt:302)
	at androidx.compose.ui.platform.AbstractComposeView.onMeasure_Original(ComposeView.android.kt:289)
	at androidx.compose.ui.platform.AbstractComposeView.onMeasure(ComposeView.android.kt)
	at android.view.View.measure_Original(View.java:27122)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:27083)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure_Original(View.java:27122)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:27083)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure_Original(View.java:27122)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:27083)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure_Original(View.java:27122)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:27083)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure_Original(View.java:27122)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:27083)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.measureView(RenderSessionImpl.java:665)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.measureLayout(RenderSessionImpl.java:261)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:380)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:454)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:120)
	at com.android.tools.rendering.RenderTask.createRenderSession(RenderTask.java:784)
	at com.android.tools.rendering.RenderTask.lambda$inflate$6(RenderTask.java:934)
	at com.android.tools.rendering.RenderExecutor$runAsyncActionWithTimeout$3.run(RenderExecutor.kt:202)
	at com.android.tools.rendering.RenderExecutor$PriorityRunnable.run(RenderExecutor.kt:316)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JoseAlcerreca** [comment]
The issue went away after working on something else for a while.
