### ISSUE TITLE
Jetsnack: crash when using navigation bar (going from home to search and going back to home)

### ISSUE THREAD

**Issue by Neovyse** [android/compose-samples#129]
I just tested Jetsnack application and I have a crash when using the navigation bar.
(going from home to search and going back to home)

**Java.lang.IllegalArgumentException: LayoutNode@4d37297 children: 0 measureBlocks: androidx.compose.ui.LayoutKt$measureBlocksOf$1@393e433 is not ready. layoutState is NeedsRelayout**

Android Studio 4.2 Preview 7
Android 9

My stack trace :
    
    --------- beginning of system
2020-08-28 17:48:37.353 3288-3517/? E/ActivityManager: TouchDown intent received, starting ActiveLaunch
2020-08-28 17:48:37.371 18751-18751/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-08-28 17:48:37.373 18751-18751/? E/Zygote: accessInfo : 1
2020-08-28 17:48:37.499 4624-27784/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
2020-08-28 17:48:37.499 4624-27784/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
2020-08-28 17:48:37.501 4624-27784/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
2020-08-28 17:48:37.666 3288-3308/? E/libprocessgroup: Failed to kill process cgroup uid 10430 pid 17199 in 219ms, 1 processes remain
2020-08-28 17:48:37.813 2883-5531/? E/BufferQueueProducer: [com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity[4846]#0] disconnect: not connected (req=1)
2020-08-28 17:48:37.818 3288-4775/? E/WindowManager: win=Window{6ffbc1b u0 com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.WindowManagerService.tryStartExitingAnimation:2755 com.android.server.wm.WindowManagerService.relayoutWindow:2453 com.android.server.wm.Session.relayoutForTranslate:302 android.view.IWindowSession$Stub.onTransact:518 com.android.server.wm.Session.onTransact:186 android.os.Binder.execTransact:739 <bottom of call stack> 
2020-08-28 17:48:39.154 3288-3665/? E/Watchdog: !@Sync 53787 [2020-08-28 17:48:39.154] FD count : 2605
2020-08-28 17:48:39.505 4624-4984/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/camera/rear/ssrm_camera_info (No such file or directory)
2020-08-28 17:48:45.735 3288-3361/? E/WindowManager: win=Window{7f6a357 u0 Splash Screen com.example.jetsnack EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:870 com.android.server.wm.AppWindowToken.destroySurfaces:851 com.android.server.wm.WindowState.onExitAnimationDone:5436 com.android.server.wm.WindowStateAnimator.onAnimationFinished:319 com.android.server.wm.WindowState.onAnimationFinished:5858 com.android.server.wm.-$$Lambda$yVRF8YoeNdTa8GR1wDStVsHu8xM.run:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0:100 
2020-08-28 17:48:46.685 9002-10934/? E/Auth: [GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION. Account: <ELLIDED:1181522219>, App: com.android.vending, Service: oauth2:https://www.googleapis.com/auth/googleplay
    rod: Long live credential not available.
        at gbz.a(:com.google.android.gms@202115026@20.21.15 (100306-313409149):19)
        at gai.a(:com.google.android.gms@202115026@20.21.15 (100306-313409149):123)
        at crk.a(:com.google.android.gms@202115026@20.21.15 (100306-313409149):231)
        at crk.a(:com.google.android.gms@202115026@20.21.15 (100306-313409149):111)
        at fyt.getAuthToken(:com.google.android.gms@202115026@20.21.15 (100306-313409149):21)
        at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:247)
        at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:114)
        at android.os.Binder.transact(Binder.java:675)
        at cte.onTransact(:com.google.android.gms@202115026@20.21.15 (100306-313409149):2)
        at android.os.Binder.transact(Binder.java:675)
        at aaah.onTransact(:com.google.android.gms@202115026@20.21.15 (100306-313409149):17)
        at android.os.Binder.execTransact(Binder.java:739)
2020-08-28 17:48:49.547 4624-4984/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/camera/rear/ssrm_camera_info (No such file or directory)
2020-08-28 17:48:59.591 4624-4984/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/camera/rear/ssrm_camera_info (No such file or directory)
2020-08-28 17:49:01.388 18751-18751/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.jetsnack, PID: 18751
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.compose.ui.platform.ViewLayer$Companion.updateDisplayList(ViewLayer.kt:259)
        at androidx.compose.ui.platform.ViewLayer.updateDisplayList(ViewLayer.kt:207)
        at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.kt:474)
        at android.view.View.draw(View.java:21871)
        at android.view.View.updateDisplayListIfDirty(View.java:20741)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
        at android.view.View.updateDisplayListIfDirty(View.java:20696)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
        at android.view.View.updateDisplayListIfDirty(View.java:20696)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
        at android.view.View.updateDisplayListIfDirty(View.java:20696)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
        at android.view.View.updateDisplayListIfDirty(View.java:20696)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4542)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4514)
        at android.view.View.updateDisplayListIfDirty(View.java:20696)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:725)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:731)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:840)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3963)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3737)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3048)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1911)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8526)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7077)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 
     Caused by: java.lang.IllegalArgumentException: LayoutNode@4d37297 children: 0 measureBlocks: androidx.compose.ui.LayoutKt$measureBlocksOf$1@393e433 is not ready. layoutState is NeedsRelayout
        at androidx.compose.ui.node.InnerPlaceable.draw(InnerPlaceable.kt:132)
        at androidx.compose.ui.node.ModifiedLayoutNode.draw(ModifiedLayoutNode.kt:81)
        at androidx.compose.ui.node.LayerWrapper$layer$1.invoke(Unknown Source:10)
        at androidx.compose.ui.node.LayerWrapper$layer$1.invoke(Unknown Source:3)
        at androidx.compose.ui.platform.ViewLayer$dispatchDraw$1$1.invoke(ViewLayer.kt:179)
        at androidx.compose.ui.platform.ViewLayer$dispatchDraw$1$1.invoke(Unknown Source:0)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1668)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:127)
2020-08-28 17:49:01.389 18751-18751/? E/AndroidRuntime:     at androidx.compose.ui.platform.AndroidComposeView.observeLayerModelReads(AndroidComposeView.kt:429)
        at androidx.compose.ui.platform.ViewLayer.dispatchDraw(ViewLayer.kt:178)
        at android.view.View.draw(View.java:21871)
        at android.view.View.updateDisplayListIfDirty(View.java:20741)
        	... 40 more
2020-08-28 17:49:01.530 3288-3316/? E/WindowManager: RemoteException occurs on reporting focusChanged, w=Window{c82aa0c u0 com.example.jetsnack/com.example.jetsnack.ui.MainActivity EXITING}
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1145)
        at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:500)
        at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3950)
        at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5472)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
2020-08-28 17:49:01.532 3288-4118/? E/WindowManager: win=Window{c82aa0c u0 com.example.jetsnack/com.example.jetsnack.ui.MainActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:870 com.android.server.wm.AppWindowToken.destroySurfaces:851 com.android.server.wm.WindowState.onExitAnimationDone:5436 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.AppWindowToken.onAnimationFinished:2398 com.android.server.wm.AppWindowToken.setVisibility:551 
2020-08-28 17:49:01.571 4624-27784/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
2020-08-28 17:49:01.571 4624-27784/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
2020-08-28 17:49:01.573 4624-27784/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
2020-08-28 17:49:01.610 16939-17032/? E/PBSessionCacheImpl: sessionId[74500108481002451] not persisted.
2020-08-28 17:49:01.627 18892-18892/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-08-28 17:49:01.629 18892-18892/? E/Zygote: accessInfo : 1
2020-08-28 17:49:01.641 18892-18892/? E/.devicesecurit: Not starting debugger since process cannot load the jdwp agent.
2020-08-28 17:49:01.746 4846-4846/? E/LiveIconManager: createLiveIconBitmap : com.sec.android.app.clockpackage apps size 1
2020-08-28 17:49:08.015 3000-3047/? E/storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
2020-08-28 17:49:09.192 3288-3665/? E/Watchdog: !@Sync 53788 [2020-08-28 17:49:09.192] FD count : 2601
2020-08-28 17:49:09.643 4624-4984/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/camera/rear/ssrm_camera_info (No such file or directory)
2020-08-28 17:49:19.680 4624-4984/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/camera/rear/ssrm_camera_info (No such file or directory)
2020-08-28 17:49:23.623 18914-18914/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-08-28 17:49:23.626 18914-18914/? E/Zygote: accessInfo : 1
2020-08-28 17:49:23.643 18914-18914/? E/ng.storyservic: Not starting debugger since process cannot load the jdwp agent.
2020-08-28 17:49:24.851 18936-18936/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-08-28 17:49:24.854 18936-18936/? E/Zygote: accessInfo : 1
2020-08-28 17:49:24.870 18936-18936/? E/ung.faceservic: Not starting debugger since process cannot load the jdwp agent.

Hope this will help you fix this problem :)

**Comment by sergeyfitis** [comment]
I have the same issue.

**Comment by Zpecter** [comment]
Same issue here.

**Comment by JoseAlcerreca** [comment]
It looks like a problem with the sample, but, have you tried in canary 8?

**Comment by Zpecter** [comment]
> It looks like a problem with the sample, but, have you tried in canary 8?

I tried with canary 8.

**Comment by Neovyse** [comment]
> It looks like a problem with the sample, but, have you tried in canary 8?

Me too, i tried with canary 8 and same issue.

**Comment by rule-po** [comment]
Same error, but on some devices there is need to make multiple switches to home tab. 
I tried it on Pixel 3 and it crashes after couple switching between tabs and then back to home. 
On Xiaomi Mi 9 after first switch back to home.

**Comment by elgunhuseynli** [comment]
Verified same error on both Emulator and Xiaomi Mi A3 devices.

**Comment by mr3y-the-programmer** [comment]
same issue with pixel 4 and AS canary 10

**Comment by Jeyhey** [comment]
Hi, could you share some insights into this issue, so that we can learn along the way? Is it an issue with the compose runtime or the way that the bottom bar is implemented (for example the way that `measure` is used)?

What are your thoughts?

**Comment by andre-artus** [comment]
Same, or very similar, issue on emulator (detail below), but occurs immediately after on activating search.



![Uploading bugreport-Jetsnack_crash_on_search.gif…]()


`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.jetsnack, PID: 5269
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.compose.ui.platform.ViewLayer$Companion.updateDisplayList(ViewLayer.kt:270)
        at androidx.compose.ui.platform.ViewLayer.updateDisplayList(ViewLayer.kt:213)
        at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.kt:554)
        at android.view.View.draw(View.java:20210)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19042)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19042)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19042)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3311)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3115)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2484)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.IllegalArgumentException: Layer is redrawn for LayoutNode in state NeedsRelayout [LayoutNode@d2888f7 children: 0 measureBlocks: androidx.compose.ui.LayoutKt$measureBlocksOf$1@a07c364]
        at androidx.compose.ui.node.LayerWrapper.invoke(LayerWrapper.kt:167)
        at androidx.compose.ui.node.LayerWrapper.invoke(Unknown Source:3)
        at androidx.compose.ui.platform.ViewLayer$dispatchDraw$1$1.invoke(ViewLayer.kt:184)
        at androidx.compose.ui.platform.ViewLayer$dispatchDraw$1$1.invoke(Unknown Source:0)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1721)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:128)
        at androidx.compose.ui.platform.AndroidComposeView.observeLayerModelReads(AndroidComposeView.kt:485)
        at androidx.compose.ui.platform.ViewLayer.dispatchDraw(ViewLayer.kt:183)
        at android.view.View.draw(View.java:20210)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at java.lang.reflect.Method.invoke(Native Method) 
        at androidx.compose.ui.platform.ViewLayer$Companion.updateDisplayList(ViewLayer.kt:270) 
        at androidx.compose.ui.platform.ViewLayer.updateDisplayList(ViewLayer.kt:213) 
        at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.kt:554) 
        at android.view.View.draw(View.java:20210) 
        at android.view.View.updateDisplayListIfDirty(View.java:19082) 
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317) 
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290) 
        at android.view.View.updateDisplayListIfDirty(View.java:19042) 
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317) 
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290) 
        at android.view.View.updateDisplayListIfDirty(View.java:19042) 
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317) 
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290) 
        at android.view.View.updateDisplayListIfDirty(View.java:19042) 
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686) 
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692) 
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801) 
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3311) 
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3115) 
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2484) 
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460) 
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:761) 
        at android.view.Choreographer.doFrame(Choreographer.java:696) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
`

`

Name: Nexus_5X_API_28

CPU/ABI: Google Play Intel Atom (x86)

Path: [..]\Nexus_5X_API_28.avd

Target: google_apis_playstore [Google Play] (API level 28)

Skin: nexus_5x

SD Card: 512M

fastboot.chosenSnapshotFile: 

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: Nexus 5X

hw.lcd.width: 1080

hw.initialOrientation: Portrait

image.androidVersion.api: 28

tag.id: google_apis_playstore

hw.mainKeys: no

hw.camera.front: emulated

avd.ini.displayname: Nexus 5X API 28

hw.gpu.mode: auto

hw.ramSize: 1536

PlayStore.enabled: true

fastboot.forceColdBoot: no

hw.cpu.ncore: 4

hw.keyboard: yes

hw.sensors.proximity: yes

hw.dPad: no

hw.lcd.height: 1920

vm.heapSize: 228

skin.dynamic: yes

hw.device.manufacturer: Google

hw.gps: yes

hw.audioInput: yes

image.sysdir.1: system-images\android-28\google_apis_playstore\x86\

showDeviceFrame: yes

hw.camera.back: virtualscene

AvdId: Nexus_5X_API_28

hw.lcd.density: 420

hw.arc: false

hw.device.hash2: MD5:ae200ad6786ec467cb9067f7b46b0fd1

fastboot.forceChosenSnapshotBoot: no

fastboot.forceFastBoot: yes

hw.trackBall: no

hw.battery: yes

hw.sdCard: yes

tag.display: Google Play

runtime.network.latency: none

disk.dataPartition.size: 6442450944

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes`

**Comment by Jeyhey** [comment]
Alpha 7 was released ... this bug still remains unclosed and uncommented.

**Comment by atsushieno** [comment]
I have no idea why, but https://github.com/android/compose-samples/issues/236 occurs on debugging run, this occurs on non-debugging run (i.e.e #236 does not reproduce on non-debug mode).

**Comment by Zpecter** [comment]
With the update to AGP 7.0.0-alpha02, it seems this has been fixed. I have tested it, and now it works.

**Comment by Neovyse** [comment]
Fixed on the AGP 7.0.0-alpha02 version
Thank you @Zpecter for testing
