### ISSUE TITLE
[JetNews] Crash on emulator 6.0

### ISSUE THREAD

**Issue by kassadin** [android/compose-samples#314]
Crash immediately after startup

```
12-11 01:04:44.953 2339-2339/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.jetnews, PID: 2339
    java.lang.IllegalStateException: Snapshot is not open
        at androidx.compose.runtime.snapshots.SnapshotKt.validateOpen(Snapshot.kt:1471)
        at androidx.compose.runtime.snapshots.SnapshotKt.access$validateOpen(Snapshot.kt)
        at androidx.compose.runtime.snapshots.MutableSnapshot.apply(Snapshot.kt:562)
        at androidx.compose.runtime.Recomposer.applyAndCheck(Recomposer.kt:402)
        at androidx.compose.runtime.Recomposer.access$applyAndCheck(Recomposer.kt)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:508)
        at androidx.compose.runtime.Composer$CompositionReferenceImpl.composeInitial$runtime_release(Composer.kt:2500)
        at androidx.compose.runtime.Composer$CompositionReferenceImpl.composeInitial$runtime_release(Composer.kt:2500)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:110)
        at androidx.compose.ui.platform.WrapperKt.actualSubcomposeInto(Wrapper.kt:124)
        at androidx.compose.ui.platform.SubcompositionKt.subcomposeInto(Subcomposition.kt:39)
        at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2.invoke(SubcomposeLayout.kt:175)
        at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2.invoke(SubcomposeLayout.kt)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.pauseObservingReads(SnapshotStateObserver.kt:147)
        at androidx.compose.ui.node.OwnerSnapshotObserver.pauseSnapshotReadObservation$ui_release(OwnerSnapshotObserver.kt:52)
        at androidx.compose.ui.node.LayoutNode.ignoreModelReads(LayoutNode.kt:1156)
        at androidx.compose.ui.layout.SubcomposeLayoutState.subcompose(SubcomposeLayout.kt:173)
        at androidx.compose.ui.layout.SubcomposeLayoutState.subcompose(SubcomposeLayout.kt:158)
        at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1.invoke(Scaffold.kt:318)
        at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1.invoke(Scaffold.kt)
        at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:67)
        at androidx.compose.ui.layout.SubcomposeLayoutState$createMeasureBlocks$1$measure$1.placeChildren(SubcomposeLayout.kt:223)
        at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:978)
        at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1721)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:126)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:59)
        at androidx.compose.ui.node.LayoutNode.layoutChildren(LayoutNode.kt:962)
        at androidx.compose.ui.node.LayoutNode.onNodePlaced$ui_release(LayoutNode.kt:950)
        at androidx.compose.ui.node.InnerPlaceable.placeAt-rMeLuDI(InnerPlaceable.kt:120)
        at androidx.compose.ui.layout.Placeable$PlacementScope.placeApparentToRealOffset-pOgwPa8(Placeable.kt:324)
        at androidx.compose.ui.layout.Placeable$PlacementScope.place-z2mxYZE(Placeable.kt:215)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-rMeLuDI(OuterMeasurablePlaceable.kt:125)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.replace(OuterMeasurablePlaceable.kt:136)
        at androidx.compose.ui.node.LayoutNode.replace$ui_release(LayoutNode.kt:831)
        at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:220)
        at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.kt:377)
        at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.kt:492)
        at android.view.View.draw(View.java:16187)
        at android.view.View.updateDisplayListIfDirty(View.java:15180)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
        at android.view.View.updateDisplayListIfDirty(View.java:15140)
    	at android.view.ViewGroup.recreateChildDispla
```

**Comment by JolandaVerhoef** [comment]
Tried to replicate with 6.0 Emulator, but seems to run fine. Can you try to run the latest version and see if this is still an issue?

**Comment by denglongfei** [comment]
Using mumu emulator will crash. Emulator address (https://mumu.163.com/)

**Comment by denglongfei** [comment]
> 尝试使用6.0 Emulator复制，但运行正常。您可以尝试运行最新版本并查看是否仍然存在问题吗？

使用mumu模拟器会崩溃。模拟器地址（https://mumu.163.com/）

**Comment by damiancioo** [comment]
Got similar error on compose 1.0.0-beta08, and constrain-layout 1.0.0-alpha07:

```
2021-06-09 12:33:06.428 dk.releaze.android.stormgeo.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dk.releaze.android.stormgeo.dev, PID: 5897
    java.lang.IllegalStateException: Snapshot is not open
        at androidx.compose.runtime.snapshots.SnapshotKt.validateOpen(Snapshot.kt:1471)
        at androidx.compose.runtime.snapshots.SnapshotKt.access$validateOpen(Snapshot.kt:1)
        at androidx.compose.runtime.snapshots.NestedMutableSnapshot.apply(Snapshot.kt:1222)
        at androidx.compose.runtime.Recomposer.applyAndCheck(Recomposer.kt:798)
        at androidx.compose.runtime.Recomposer.access$applyAndCheck(Recomposer.kt:102)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1043)
        at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:2974)
        at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:2974)
        at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:2974)
        at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:2974)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:432)
        at androidx.compose.ui.graphics.vector.VectorPainter.composeVector(VectorPainter.kt:157)
        at androidx.compose.ui.graphics.vector.VectorPainter.RenderVector$ui_release(VectorPainter.kt:177)
        at androidx.compose.ui.graphics.vector.VectorPainterKt.rememberVectorPainter-mlNsNFs(VectorPainter.kt:83)
        at androidx.compose.ui.graphics.vector.VectorPainterKt.rememberVectorPainter(VectorPainter.kt:106)
        at androidx.compose.ui.res.PainterResources_androidKt.painterResource(PainterResources.android.kt:67)
        at dk.releaze.android.stormgeo.feature.frontpage.compose.DayCardKt$DayCard$1$invoke$$inlined$ConstraintLayout$1.invoke(ConstraintLayout.kt:1590)
        at dk.releaze.android.stormgeo.feature.frontpage.compose.DayCardKt$DayCard$1$invoke$$inlined$ConstraintLayout$1.invoke(ConstraintLayout.kt:82)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.ui.layout.LayoutKt.MultiMeasureLayout(Layout.kt:494)
        at dk.releaze.android.stormgeo.feature.frontpage.compose.DayCardKt$DayCard$1.invoke(DayCard.kt:208)
        at dk.releaze.android.stormgeo.feature.frontpage.compose.DayCardKt$DayCard$1.invoke(DayCard.kt:54)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:268)
        at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:255)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:215)
        at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:252)
        at androidx.compose.material.SurfaceKt.Surface-BK04aR4(Surface.kt:215)
        at androidx.compose.material.CardKt.Card-BK04aR4(Card.kt:126)
        at dk.releaze.android.stormgeo.feature.frontpage.compose.DayCardKt.DayCard(DayCard.kt:45)
        at dk.releaze.android.stormgeo.feature.frontpage.compose.DailyForecastSectionKt$DailyForecastSection$2$1$2.invoke(DailyForecastSection.kt:99)
        at dk.releaze.android.stormgeo.feature.frontpage.compose.DailyForecastSectionKt$DailyForecastSection$2$1$2.invoke(DailyForecastSection.kt:98)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.material.TabKt$Tab$5.invoke(Tab.kt:496)
        at androidx.compose.material.TabKt$Tab$5.invoke(Tab.kt:239)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
    	at androidx.compose.runtime.internal.
```

**Comment by marcouberti** [comment]
It happened also on my 6.0 emulator. Solved increasing the emulator disk memory.

**Comment by wv1124** [comment]
还真是只MuMu模似器会报错，真机没有

**Comment by Kolyall** [comment]
buildGradleVersion = "8.1.1"
androidMinSdkVersion = '23'
androidTargetSdkVersion = '33'
androidCompileSdkVersion = '34'
kotlinVersion = '1.9.10'
composeCompilerVersion = '1.5.3'
composeVersion = '1.5.0'
```
 java.lang.IllegalStateException: Snapshot is not open
                                 	at androidx.compose.runtime.snapshots.SnapshotKt.validateOpen(Snapshot.kt:1851)
                                 	at androidx.compose.runtime.snapshots.SnapshotKt.access$validateOpen(Snapshot.kt:1)
                                 	at androidx.compose.runtime.snapshots.MutableSnapshot.apply(Snapshot.kt:729)
                                 	at androidx.compose.runtime.snapshots.TransparentObserverMutableSnapshot.apply(Snapshot.kt:1523)
                                 	at androidx.compose.runtime.Recomposer.applyAndCheck(Recomposer.kt:1174)
                                 	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1560)
                                 	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:4007)
                                 	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:520)
                                 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcomposeInto(SubcomposeLayout.kt:721)
                                 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:694)
                                 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:685)
                                 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:669)
                                 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:1014)
                                 	at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1.invoke(Scaffold.kt:250)
                                 	at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1.invoke(Scaffold.kt:243)
                                 	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:70)
                                 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1$measure$1.placeChildren(SubcomposeLayout.kt:879)
                                 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.kt:365)
                                 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.kt:357)
                                 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2299)
                                 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
                                 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
                                 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:83)
                                 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.layoutChildren(LayoutNodeLayoutDelegate.kt:357)
                                 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.onNodePlaced$ui_release(LayoutNodeLayoutDelegate.kt:493)
                                 	at androidx.compose.ui.node.InnerNodeCoordinator.placeAt-f8xVGno(InnerNodeCoordinator.kt:160)
                                 	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:34)
                                 	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:450)
                                 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:683)
                                 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:678)
                                 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2299)
                                 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
                                 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
                                 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutModifierSnapshotReads$ui_release(OwnerSnapshotObserver.kt:98)
                                 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeOuterCoordinator-f8xVGno(LayoutNodeLayoutDelegate.kt:678)
                                 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeAt-f8xVGno(Layo
16:23:04.034 Error            D  ERR: exClass=java.lang.IllegalStateException
16:23:04.034 Error            D  ERR: exMsg=Snapshot is not open
16:23:04.034 Error            D  ERR: file=Snapshot.kt
16:23:04.034 Error            D  ERR: class=androidx.compose.runtime.snapshots.SnapshotKt
16:23:04.034 Error            D  ERR: method=validateOpen line=1851
16:23:04.034 Error            D  ERR: stack=java.lang.IllegalStateException: Snapshot is not open
                                 	at androidx.compose.runtime.snapshots.SnapshotKt.validateOpen(Snapshot.kt:1851)
                                 	at androidx.compose.runtime.snapshots.SnapshotKt.access$validateOpen(Snapshot.kt:1)
                                 	at androidx.compose.runtime.snapshots.MutableSnapshot.apply(Snapshot.kt:729)
                                 	at androidx.compose.runtime.snapshots.TransparentObserverMutableSnapshot.apply(Snapshot.kt:1523)
                                 	at androidx.compose.runtime.Recomposer.applyAndCheck(Recomposer.kt:1174)
                                 	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1560)
                                 	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:4007)
                                 	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:520)
                                 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcomposeInto(SubcomposeLayout.kt:721)
                                 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:694)
                                 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:685)
                                 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:669)
                                 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:1014)
                                 	at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1.invoke(Scaffold.kt:250)
                                 	at androidx.compose.material.ScaffoldKt$ScaffoldLayout$1$1$1.invoke(Scaffold.kt:243)
                                 	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:70)
                                 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1$measure$1.placeChildren(SubcomposeLayout.kt:879)
                                 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.kt:365)
                                 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.kt:357)
                                 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2299)
                                 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
                                 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
                                 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:83)
                                 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.layoutChildren(LayoutNodeLayoutDelegate.kt:357)
                                 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.onNodePlaced$ui_release(LayoutNodeLayoutDelegate.kt:493)
                                 	at androidx.compose.ui.node.InnerNodeCoordinator.placeAt-f8xVGno(InnerNodeCoordinator.kt:160)
                                 	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:34)
                                 	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:450)
                                 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:683)
                                 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:678)
                                 	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2299)
                                 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
                                 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
                                 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutModifierSnapshotReads$ui_release(OwnerSnapshotObserver.kt:98)
                                 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeOuterCoordinator-f8xVGno(LayoutNodeLayoutDelegate.kt:678)
                                 	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeAt-f8xVGno(LayoutNodeLayoutDelegate.kt:656)
                                 	at androidx.compose.ui.layout.P
16:23:04.034 Error            D  ERR: TOTAL BYTES WRITTEN: 29752
```

**Comment by Kolyall** [comment]
Works correctly after recreation of the emulator API 23
