### ISSUE TITLE
[Jetchat] Crash on Google Pixel 1(release build).

### ISSUE THREAD

**Issue by ashtanko** [android/compose-samples#326]
Crash immediately after startup
```

E/ModuleIdSetter: exception when setting module id
    java.lang.IllegalStateException: Unable to get current module info in ModuleManager created with non-module Context
        at com.google.android.chimera.config.ModuleManager.getCurrentModule(:com.google.android.gms@204516037@20.45.16 (120400-344294571):2)
        at afzn.a(:com.google.android.gms@204516037@20.45.16 (120400-344294571):4)
        at afzq.Z(:com.google.android.gms@204516037@20.45.16 (120400-344294571):1)
        at afwb.a(Unknown Source:0)
        at sew.a(:com.google.android.gms@204516037@20.45.16 (120400-344294571):0)
        at sba.f(:com.google.android.gms@204516037@20.45.16 (120400-344294571):1)
        at say.e(:com.google.android.gms@204516037@20.45.16 (120400-344294571):1)
        at sds.p(:com.google.android.gms@204516037@20.45.16 (120400-344294571):2)
        at sds.v(:com.google.android.gms@204516037@20.45.16 (120400-344294571):3)
        at sds.e(:com.google.android.gms@204516037@20.45.16 (120400-344294571):2)
        at sdw.handleMessage(:com.google.android.gms@204516037@20.45.16 (120400-344294571):71)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at afow.iE(:com.google.android.gms@204516037@20.45.16 (120400-344294571):0)
        at afow.dispatchMessage(:com.google.android.gms@204516037@20.45.16 (120400-344294571):11)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)

   Process: com.example.compose.jetchat, PID: 19260
    java.lang.NullPointerException: throw with null exception
        at sw0.v(SourceFile:2)
        at bl.x(SourceFile:5)
        at tc.q0(SourceFile:1)
        at al.o(SourceFile:1)
        at yj.o(SourceFile:1)
        at yj.o(SourceFile:1)
        at yj.o(SourceFile:1)
        at qq0.i0(SourceFile:3)
        at o90.v(SourceFile:2)
        at rk.a(SourceFile:6)
        at rk.v(Unknown Source:8)
        at qq0.k(SourceFile:51)
        at rn.j(SourceFile:48)
        at jn.x(SourceFile:72)
        at rk.x(SourceFile:5)
        at qq0.j(SourceFile:51)
        at n41.x(SourceFile:12)
        at rk.x(SourceFile:5)
        at tc.n(SourceFile:44)
        at qq0.p(SourceFile:11)
        at qq0.o(SourceFile:41)
        at rn.f(SourceFile:13)
        at tm.a(SourceFile:19)
        at tm.x(SourceFile:2)
        at rk.x(SourceFile:5)
        at qq0.j(SourceFile:51)
        at u71.a(SourceFile:6)
        at wd0.x(SourceFile:5)
        at rk.x(SourceFile:5)
        at qq0.j(SourceFile:51)
        at ia0.b(SourceFile:156)
        at r81.a(SourceFile:12)
        at tm.a(SourceFile:2)
        at tm.x(SourceFile:1)
        at rk.x(SourceFile:5)
        at qq0.j(SourceFile:51)
        at com.example.compose.jetchat.conversation.ConversationFragment$a.x(SourceFile:8)

```

**Comment by nickbutcher** [comment]
Can you provide a non-obfuscated stack trace?

**Comment by prituladima** [comment]
I'm not expecting for fix but I hope to save time to some people and help developers.

Let me add some logs and screenshots that may help.
Pixel 2 is constantly crashing. Nexus 5 is working with no problem.
<img width="1409" alt="Screenshot 2021-02-08 at 19 52 41" src="https://user-images.githubusercontent.com/6098996/107267734-98942500-6a47-11eb-9f25-e7d6c3acaa5e.png">

Crash that looks the same like above.
```
2021-02-08 16:26:15.104 8357-8408/? E/ModuleIdSetter: exception when setting module id
    java.lang.IllegalStateException: Unable to get current module info in ModuleManager created with non-module Context
        at com.google.android.chimera.config.ModuleManager.getCurrentModule(:com.google.android.gms@205016040@20.50.16 (120700-351607135):2)
        at aghc.a(:com.google.android.gms@205016040@20.50.16 (120700-351607135):4)
        at aghf.aa(:com.google.android.gms@205016040@20.50.16 (120700-351607135):1)
        at agdq.a(Unknown Source:3)
        at smj.a(:com.google.android.gms@205016040@20.50.16 (120700-351607135):0)
        at sin.f(:com.google.android.gms@205016040@20.50.16 (120700-351607135):1)
        at sil.e(:com.google.android.gms@205016040@20.50.16 (120700-351607135):1)
        at slf.p(:com.google.android.gms@205016040@20.50.16 (120700-351607135):2)
        at slf.v(:com.google.android.gms@205016040@20.50.16 (120700-351607135):3)
        at slf.d(:com.google.android.gms@205016040@20.50.16 (120700-351607135):2)
        at slf.a(:com.google.android.gms@205016040@20.50.16 (120700-351607135):7)
        at slf.m(:com.google.android.gms@205016040@20.50.16 (120700-351607135):1)
        at tbr.a(:com.google.android.gms@205016040@20.50.16 (120700-351607135):0)
        at tas.a(:com.google.android.gms@205016040@20.50.16 (120700-351607135):8)
        at taj.d(:com.google.android.gms@205016040@20.50.16 (120700-351607135):0)
        at tam.handleMessage(:com.google.android.gms@205016040@20.50.16 (120700-351607135):23)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at afwl.iD(:com.google.android.gms@205016040@20.50.16 (120700-351607135):0)
        at afwl.dispatchMessage(:com.google.android.gms@205016040@20.50.16 (120700-351607135):11)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)

```
Pixel 2 emulator
```


Name: Nexus_5_API_29

CPU/ABI: Google Play Intel Atom (x86)

Path: /Users/user/.android/avd/Nexus_5_API_29.avd

Target: google_apis_playstore [Google Play] (API level 29)

Skin: nexus_5

SD Card: 512M

fastboot.chosenSnapshotFile: 

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: Nexus 5

hw.lcd.width: 1080

hw.initialOrientation: Portrait

image.androidVersion.api: 29

tag.id: google_apis_playstore

hw.mainKeys: no

hw.camera.front: emulated

avd.ini.displayname: Nexus 5 API 29

hw.gpu.mode: auto

hw.ramSize: 1536

PlayStore.enabled: true

fastboot.forceColdBoot: no

hw.cpu.ncore: 4

hw.keyboard: yes

hw.sensors.proximity: yes

hw.dPad: no

hw.lcd.height: 1920

vm.heapSize: 128

skin.dynamic: yes

hw.device.manufacturer: Google

hw.gps: yes

hw.audioInput: yes

image.sysdir.1: system-images/android-29/google_apis_playstore/x86/

showDeviceFrame: yes

hw.camera.back: virtualscene

AvdId: Nexus_5_API_29

hw.lcd.density: 480

hw.arc: false

hw.device.hash2: MD5:041eb4f348dec9fd18091e32004fae73

fastboot.forceChosenSnapshotBoot: no

fastboot.forceFastBoot: yes

hw.trackBall: no

hw.battery: yes

hw.sdCard: yes

tag.display: Google Play

runtime.network.latency: none

disk.dataPartition.size: 6442450944

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes
```

Nexus 5
```


Name: Nexus_5_API_29

CPU/ABI: Google Play Intel Atom (x86)

Path: /Users/user/.android/avd/Nexus_5_API_29.avd

Target: google_apis_playstore [Google Play] (API level 29)

Skin: nexus_5

SD Card: 512M

fastboot.chosenSnapshotFile: 

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: Nexus 5

hw.lcd.width: 1080

hw.initialOrientation: Portrait

image.androidVersion.api: 29

tag.id: google_apis_playstore

hw.mainKeys: no

hw.camera.front: emulated

avd.ini.displayname: Nexus 5 API 29

hw.gpu.mode: auto

hw.ramSize: 1536

PlayStore.enabled: true

fastboot.forceColdBoot: no

hw.cpu.ncore: 4

hw.keyboard: yes

hw.sensors.proximity: yes

hw.dPad: no

hw.lcd.height: 1920

vm.heapSize: 128

skin.dynamic: yes

hw.device.manufacturer: Google

hw.gps: yes

hw.audioInput: yes

image.sysdir.1: system-images/android-29/google_apis_playstore/x86/

showDeviceFrame: yes

hw.camera.back: virtualscene

AvdId: Nexus_5_API_29

hw.lcd.density: 480

hw.arc: false

hw.device.hash2: MD5:041eb4f348dec9fd18091e32004fae73

fastboot.forceChosenSnapshotBoot: no

fastboot.forceFastBoot: yes

hw.trackBall: no

hw.battery: yes

hw.sdCard: yes

tag.display: Google Play

runtime.network.latency: none

disk.dataPartition.size: 6442450944

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes
```

**Comment by prituladima** [comment]
UPD: Unfortunately any 29 emulator crash in 1 or 2 hours of usage.

**Comment by JoseAlcerreca** [comment]
What we need is an non-obfuscated version of the jetchat stack trace. The latest one is just an unrelated gmscore crash.
