### ISSUE TITLE
[Owl] Render Problem

### ISSUE THREAD

**Issue by ensozos** [android/compose-samples#334]
Android Studio Arctic Fox | 2020.3.1 Canary 3
Build #AI-202.7319.50.2031.7019041, built on December 8, 2020
Runtime version: 11.0.8+10-b944.6842174 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 12
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: mobi.hsz.idea.gitignore, org.jetbrains.kotlin, com.google.mad-scorecard

I am getting the following error when I try to preview the composable. I tried several things to solve the problem including clean, rebuild, invalidate and restart.

> java.lang.IllegalStateException: AmbientWindowInsets value not available. Are you using ProvideWindowInsets?
	at dev.chrisbanes.accompanist.insets.ComposeInsets__InsetsKt$AmbientWindowInsets$1.invoke(Insets.kt:138)
	at dev.chrisbanes.accompanist.insets.ComposeInsets__InsetsKt$AmbientWindowInsets$1.invoke(Insets.kt)
	at androidx.compose.runtime.LazyValueHolder$current$2.invoke(ValueHolders.kt:33)
	at _layoutlib_._internal_.kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.compose.runtime.LazyValueHolder.getCurrent(ValueHolders.kt:30)
	at androidx.compose.runtime.LazyValueHolder.getValue(ValueHolders.kt:36)
	at androidx.compose.runtime.CompositionReference.getAmbient$runtime_release(CompositionReference.kt:54)
	at androidx.compose.runtime.Composer.resolveAmbient(Composer.kt:1343)
	at androidx.compose.runtime.Composer.consume(Composer.kt:1315)
	at dev.chrisbanes.accompanist.insets.ComposeInsets__PaddingKt$statusBarsPadding$1.invoke(Padding.kt:221)
	at dev.chrisbanes.accompanist.insets.ComposeInsets__PaddingKt$statusBarsPadding$1.invoke(Padding.kt)
	at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt:75)
	at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt)
	at androidx.compose.ui.Modifier$Element$DefaultImpls.foldIn(Modifier.kt:107)
	at androidx.compose.ui.ComposedModifier.foldIn(ComposedModifier.kt:47)
	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
	at androidx.compose.ui.ComposedModifierKt.materialize(ComposedModifier.kt:70)
	at androidx.compose.ui.layout.LayoutKt$materializerOf$1.invoke(Layout.kt:249)
	at androidx.compose.ui.layout.LayoutKt$materializerOf$1.invoke(Layout.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:155)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at com.example.owl.ui.course.CourseDetailsKt.Lessons-yeU6478(CourseDetails.kt:719)
	at com.example.owl.ui.course.CourseDetailsKt.access$Lessons-yeU6478(CourseDetails.kt)
	at com.example.owl.ui.course.CourseDetailsKt$LessonsSheetPreview$1$1.invoke(CourseDetails.kt:521)
	at com.example.owl.ui.course.CourseDetailsKt$LessonsSheetPreview$1$1.invoke(CourseDetails.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
	at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:111)
	at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.ui.layout.LayoutKt.Layout(Layout.kt:674)
	at androidx.compose.material.SurfaceKt.SurfaceLayout(Surface.kt:137)
	at androidx.compose.material.SurfaceKt.Surface-biUpMIw(Surface.kt:102)
	at com.example.owl.ui.course.CourseDetailsKt$LessonsSheetPreview$1.invoke(CourseDetails.kt:520)
	at com.example.owl.ui.course.CourseDetailsKt$LessonsSheetPreview$1.invoke(CourseDetails.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
	at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:246)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:83)
	at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
	at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:74)
	at com.example.owl.ui.theme.ThemeKt$OwlTheme$1.invoke(Theme.kt:133)
	at com.example.owl.ui.theme.ThemeKt$OwlTheme$1.invoke(Theme.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
	at com.example.owl.ui.theme.ThemeKt.OwlTheme(Theme.kt:129)
	at com.example.owl.ui.theme.ThemeKt.PinkTheme(Theme.kt:110)
	at com.example.owl.ui.course.CourseDetailsKt.LessonsSheetPreview(CourseDetails.kt:518)
	at com.example.owl.ui.course.CourseDetailsKt.LessonsSheetOpenDarkPreview(CourseDetails.kt:510)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at androidx.compose.ui.tooling.preview.PreviewUtilsKt.invokeComposableMethod(PreviewUtils.kt:141)
	at androidx.compose.ui.tooling.preview.PreviewUtilsKt.invokeComposableViaReflection(PreviewUtils.kt:180)
	at androidx.compose.ui.tooling.preview.ComposeViewAdapter$init$3$2$composable$1.invoke(ComposeViewAdapter.kt:437)
	at androidx.compose.ui.tooling.preview.ComposeViewAdapter$init$3$2$composable$1.invoke(ComposeViewAdapter.kt)
	at androidx.compose.ui.tooling.preview.ComposeViewAdapter$init$3$2.invoke(ComposeViewAdapter.kt:471)
	at androidx.compose.ui.tooling.preview.ComposeViewAdapter$init$3$2.invoke(ComposeViewAdapter.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
	at androidx.compose.ui.tooling.InspectableKt.Inspectable(Inspectable.kt:65)
	at androidx.compose.ui.tooling.preview.ComposeViewAdapter$WrapPreview$1.invoke(ComposeViewAdapter.kt:384)
	at androidx.compose.ui.tooling.preview.ComposeViewAdapter$WrapPreview$1.invoke(ComposeViewAdapter.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
	at androidx.compose.ui.tooling.preview.ComposeViewAdapter.WrapPreview(ComposeViewAdapter.kt:383)
	at androidx.compose.ui.tooling.preview.ComposeViewAdapter.access$WrapPreview(ComposeViewAdapter.kt)
	at androidx.compose.ui.tooling.preview.ComposeViewAdapter$init$3.invoke(ComposeViewAdapter.kt:430)
	at androidx.compose.ui.tooling.preview.ComposeViewAdapter$init$3.invoke(ComposeViewAdapter.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.kt:253)
	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.kt:112)
	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
	at androidx.compose.ui.platform.AmbientsKt.ProvideCommonAmbients(Ambients.kt:274)
	at androidx.compose.ui.platform.AndroidAmbientsKt$ProvideAndroidAmbients$3.invoke(AndroidAmbients.kt:176)
	at androidx.compose.ui.platform.AndroidAmbientsKt$ProvideAndroidAmbients$3.invoke(AndroidAmbients.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
	at androidx.compose.ui.platform.AndroidAmbientsKt.ProvideAndroidAmbients(AndroidAmbients.kt:168)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.kt:251)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.kt:250)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.kt)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
	at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt)
	at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:2904)
	at androidx.compose.runtime.Composer.composeInitial(Composer.kt:2070)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:353)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:109)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.kt:235)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.kt)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.kt:545)
	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.kt:226)
	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.kt:275)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.kt:233)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.kt)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.kt:610)
	at android.view.View.dispatchAttachedToWindow(View.java:20479)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3489)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
	at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:44)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:361)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:431)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:141)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:696)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$6(RenderTask.java:852)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$2.run(RenderExecutor.kt:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by j-ns** [comment]
It looks like you are missing a call for `ProvideWindowInsets`:

```
@Preview
@Composable
fun Preview() {
    ProvideWindowInsets {
        YourTheme() {
            YourComposable()
        }
    }
}
```

**Comment by ensozos** [comment]
Yes, that was the problem, thank you. But I don't get it. Why we need this in @Preview methods and why they didn't have this on the sample projects (or even mention it on codelabs)?

**Comment by chrisbanes** [comment]
The comment @j-ns has the right fix 👍
