### ISSUE TITLE
[Jetcaster] Crash when launched offline

### ISSUE THREAD

**Issue by ansman** [android/compose-samples#339]
If you launch Jetcaster without being connected to the internet it crashes with the following stacktrace:
```
01-07 11:48:52.187 31325 31325 E AndroidRuntime: FATAL EXCEPTION: main
01-07 11:48:52.187 31325 31325 E AndroidRuntime: Process: com.example.jetcaster, PID: 31325
01-07 11:48:52.187 31325 31325 E AndroidRuntime: java.net.ConnectException: Failed to connect to /10.10.1.2:9090
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:261)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:201)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	Suppressed: java.net.ConnectException: Failed to connect to /10.10.1.2:9090
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 		at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 		... 17 more
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	Caused by: java.net.ConnectException: failed to connect to /10.10.1.2 (port 9090) from /10.10.1.28 (port 37242) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 		at libcore.io.IoBridge.isConnected(IoBridge.java:287)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 		at libcore.io.IoBridge.connectErrno(IoBridge.java:192)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 		at libcore.io.IoBridge.connect(IoBridge.java:134)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 		at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 		at java.net.Socket.connect(Socket.java:621)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 		at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 		at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 		... 18 more
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 		at libcore.io.IoBridge.isConnected(IoBridge.java:274)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 		... 28 more
01-07 11:48:52.187 31325 31325 E AndroidRuntime: Caused by: java.net.ConnectException: failed to connect to /10.10.1.2 (port 9090) from /10.10.1.28 (port 37246) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at libcore.io.IoBridge.isConnected(IoBridge.java:287)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:192)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at libcore.io.IoBridge.connect(IoBridge.java:134)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at java.net.Socket.connect(Socket.java:621)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	... 19 more
01-07 11:48:52.187 31325 31325 E AndroidRuntime: Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	at libcore.io.IoBridge.isConnected(IoBridge.java:274)
01-07 11:48:52.187 31325 31325 E AndroidRuntime: 	... 29 more
```

**Comment by yrezgui** [comment]
I found the bug during the holidays. If you launch the app for the first time without internet, it crashs. I guess we're not checking if the device is connected. I'll handle it
