### ISSUE TITLE
Crash on Compose UI 

### ISSUE THREAD

**Issue by anuj72** [android/compose-samples#379]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.skydoves.disneycompose, PID: 7460
    java.lang.IllegalStateException: Snapshot is not open
        at androidx.compose.runtime.snapshots.SnapshotKt.validateOpen(Snapshot.kt:1462)
        at androidx.compose.runtime.snapshots.SnapshotKt.access$validateOpen(Snapshot.kt)
        at androidx.compose.runtime.snapshots.MutableSnapshot.apply(Snapshot.kt:556)
        at androidx.compose.runtime.Recomposer.applyAndCheck(Recomposer.kt:616)
        at androidx.compose.runtime.Recomposer.access$applyAndCheck(Recomposer.kt)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:752)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:521)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt)
        at androidx.compose.runtime.dispatch.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.kt:34)
        at androidx.compose.runtime.dispatch.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.kt:111)
        at androidx.compose.runtime.dispatch.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.kt)
        at androidx.compose.runtime.dispatch.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.kt:71)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
        at android.view.Choreographer.doFrame(Choreographer.java:603)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by JoseAlcerreca** [comment]
Not related to samples
