### ISSUE TITLE
[JetNews] Clash when scroll the Sceen of article "Collections and sequences in Kotlin"

### ISSUE THREAD

**Issue by wjploop** [android/compose-samples#510]
The error trace:
```
2021-05-08 17:42:19.429 5482-5482/com.example.jetnews E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.jetnews, PID: 5482
    java.lang.IndexOutOfBoundsException: setSpan (463 ... 3600) ends beyond length 475
        at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:491)
        at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:197)
        at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:184)
        at android.text.SpannableString.setSpan(SpannableString.java:60)
        at androidx.compose.ui.text.platform.extensions.SpannableExtensions_androidKt$setFontAttributes$1.invoke(SpannableExtensions.android.kt:259)
        at androidx.compose.ui.text.platform.extensions.SpannableExtensions_androidKt$setFontAttributes$1.invoke(SpannableExtensions.android.kt:258)
        at androidx.compose.ui.text.platform.extensions.SpannableExtensions_androidKt.flattenFontStylesAndApply(SpannableExtensions.android.kt:327)
        at androidx.compose.ui.text.platform.extensions.SpannableExtensions_androidKt.setFontAttributes(SpannableExtensions.android.kt:255)
        at androidx.compose.ui.text.platform.extensions.SpannableExtensions_androidKt.setSpanStyles(SpannableExtensions.android.kt:146)
        at androidx.compose.ui.text.platform.AndroidParagraphHelper_androidKt.createCharSequence(AndroidParagraphHelper.android.kt:57)
        at androidx.compose.ui.text.platform.AndroidParagraphIntrinsics.<init>(AndroidParagraphIntrinsics.android.kt:72)
        at androidx.compose.ui.text.platform.AndroidParagraphIntrinsics_androidKt.ActualParagraphIntrinsics(AndroidParagraphIntrinsics.android.kt:127)
        at androidx.compose.ui.text.ParagraphIntrinsicsKt.ParagraphIntrinsics(ParagraphIntrinsics.kt:54)
        at androidx.compose.ui.text.MultiParagraphIntrinsics.<init>(MultiParagraphIntrinsics.kt:78)
        at androidx.compose.foundation.text.TextDelegate.layoutIntrinsics(TextDelegate.kt:125)
        at androidx.compose.foundation.text.TextDelegate.layoutText-K40F9xA(TextDelegate.kt:149)
        at androidx.compose.foundation.text.TextDelegate.layout-NN6Ew-U(TextDelegate.kt:226)
        at androidx.compose.foundation.text.TextController$measurePolicy$1.measure-3p2s80s(CoreText.kt:249)
        at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:45)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:108)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:108)
        at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:213)
        at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:37)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:108)
        at androidx.compose.foundation.layout.PaddingModifier.measure-3p2s80s(Padding.kt:363)
        at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:37)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:95)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:94)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:121)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:75)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:63)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:94)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:68)
        at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1172)
        at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1.measure-3p2s80s(Box.kt:115)
        at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:45)
        at androidx.compose.foundation.layout.PaddingModifier.measure-3p2s80s(Padding.kt:363)
```

**Comment by Abhimanyu14** [comment]
Raised a PR addressing this app crash.
PR link - https://github.com/android/compose-samples/pull/511
