### ISSUE TITLE
[Material Catalog] [v1.0.0-beta08] [APK] Missing certificates 

### ISSUE THREAD

**Issue by pranavpandey** [android/compose-samples#579]
The `material-catalog-debug.apk` attached as `asset` for the release [v1.0.0-beta08](https://github.com/android/compose-samples/releases/tag/v1.0.0-beta08) cannot be installed on API level 23 and below due to the missing certificates.

- I have extracted the APK and there is no certificate present inside the `META-INF` folder.
- Please check the `logcat` from the Android emulator (API 23):

```
06-22 07:07:03.610 2385-2397/com.android.defcontainer D/DefContainer: Copying /data/local/tmp/material-catalog-debug.apk to base.apk
06-22 07:07:03.641 1585-1609/system_process W/PackageManager: Failed collect during installPackageLI
    android.content.pm.PackageParser$PackageParserException: Failed to collect certificates from /data/app/vmdl1080235947.tmp/base.apk
        at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1130)
        at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1057)
        at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:12196)
        at com.android.server.pm.PackageManagerService.-wrap25(PackageManagerService.java)
        at com.android.server.pm.PackageManagerService$9.run(PackageManagerService.java:10156)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.android.server.ServiceThread.run(ServiceThread.java:46)
     Caused by: java.lang.NullPointerException: Attempt to get length of null array
        at java.util.jar.Manifest.read(Manifest.java:201)
        at java.util.jar.Manifest.<init>(Manifest.java:106)
        at java.util.jar.StrictJarFile.<init>(StrictJarFile.java:66)
        at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1072)
        at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1057) 
        at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:12196) 
        at com.android.server.pm.PackageManagerService.-wrap25(PackageManagerService.java) 
        at com.android.server.pm.PackageManagerService$9.run(PackageManagerService.java:10156) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
        at com.android.server.ServiceThread.run(ServiceThread.java:46) 
```

**Comment by nickbutcher** [comment]
@ricknout (I can't seem to assign to you Nick?!)

**Comment by ricknout** [comment]
Can you please try with the APK for the `1.0.0-rc01` release and let me know if the issue persists?

**Comment by pranavpandey** [comment]
It's working fine with `1.0.0-rc01` release.
I have tested it on a physical device (API 22) and an Android emulator (API 23). 

Thanks!

**Comment by ricknout** [comment]
Great! @nickbutcher I guess you can close this issue now 👍
