### ISSUE TITLE
JetCaster crash when click on "follow" with talkback

### ISSUE THREAD

**Issue by FannyDemey** [android/compose-samples#634]
Hi 

I've tested Jetcaster app with Talkback to make accessibility improvement. I came across this bug that makes the app crash systematically : 
Way to reproduce : 
- Start the app using Talkback
- When focus is on a button to follow a new podcast
- Then double tap.
- RESULT : => app crash with this message and we are not able to restart the app (we have to remove data to be able to do so)
`2021-08-30 11:10:10.025 19023-19023/com.example.jetcaster E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.jetcaster, PID: 19023
    java.lang.NullPointerException
        at com.google.accompanist.pager.Pager$Pager$semanticsAxisRange$1$1.invoke(Pager.kt:421)
        at com.google.accompanist.pager.Pager$Pager$semanticsAxisRange$1$1.invoke(Pager.kt:234)
        at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.populateAccessibilityNodeInfoProperties(AndroidComposeViewAccessibilityDelegateCompat.android.kt:647)
        at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.createNodeInfo(AndroidComposeViewAccessibilityDelegateCompat.android.kt:297)
        at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.access$createNodeInfo(AndroidComposeViewAccessibilityDelegateCompat.android.kt:101)
        at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat$MyNodeProvider.createAccessibilityNodeInfo(AndroidComposeViewAccessibilityDelegateCompat.android.kt:2273)
        at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:1034)
        at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:341)
        at android.view.AccessibilityInteractionController.access$400(AccessibilityInteractionController.java:75)
        at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1393)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7697)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

I planned to have a look about this bug later but if you have any idea, let me know :) 

Regards

Fanny

**Comment by mystic001** [comment]
please ny instruction how to start this applications after cloning the repository

**Comment by riggaroo** [comment]
@JolandaVerhoef can this one be closed?

**Comment by JolandaVerhoef** [comment]
Checked in Jetcaster and I can't reproduce the issue anymore. Will close this issue. @FannyDemey feel free to re-open if there's still an issue for you!
