### ISSUE TITLE
[Jetsnack] Crashes when fast switching between two bottom nav destination

### ISSUE THREAD

**Issue by NitroG42** [android/compose-samples#664]
When doing this sequence : Home -> Search -> Home (or any other destinations)
The following crash will occurs : 
```
com.example.jetsnack E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.jetsnack, PID: 19022
    java.lang.IllegalStateException: You cannot access the NavBackStackEntry's ViewModels until it is added to the NavController's back stack (i.e., the Lifecycle of the NavBackStackEntry reaches the CREATED state).
        at androidx.navigation.NavBackStackEntry.getViewModelStore(NavBackStackEntry.kt:174)
        at androidx.lifecycle.ViewModelProvider.<init>(ViewModelProvider.java:99)
        at androidx.lifecycle.viewmodel.compose.ViewModelKt.get(ViewModel.kt:82)
        at androidx.lifecycle.viewmodel.compose.ViewModelKt.viewModel(ViewModel.kt:72)
        at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:86)
        at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
        at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:51)
        at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:50)
```

I have a similar issue (using a lifecycle observer, doing the same sequence will moev the Home's lifecycle from LifecycleOwner.current going to ON_STOP then not moving back again to  Lifecycle.Event.ON_START)
Not sure what are the possible workaround, where does the issue lies (it is the lifecycle CREATE/OnStop event issue ? from https://developer.android.com/topic/libraries/architecture/lifecycle#onStop-and-savedState )

It affects current commit and also 1.0.2 release (and maybe previous too)

**Comment by NitroG42** [comment]
Ok, the bug comes from the version of navigation library : https://issuetracker.google.com/issues/195860509 It doesn't happens when updating to nav-compose07 or greater.
Unfortunatelly it doesn't fix my issue but that's another problem !
I leave the issue opened just in case but you can close it if you want.
