### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hardik-trivedi** [android/compose-samples#812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

Rally

### What happened?

I am trying to refer to a screenshot testing example from Rally app. In my app espresso test fails on following line 
val bitmap = node.captureToImage().asAndroidBitmap()

I have attached the exact logs I get.

It seems like there is some dependency versions misalignment. I tried to keep them as per repo but still no luck.

### Relevant logcat output

```shell
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/test/platform/graphics/HardwareRendererCompat;
at androidx.compose.ui.test.android.WindowCapture_androidKt.withDrawingEnabled(WindowCapture.android.kt:55)
at androidx.compose.ui.test.android.WindowCapture_androidKt.captureRegionToImage(WindowCapture.android.kt:46)
at androidx.compose.ui.test.AndroidImageHelpers_androidKt.captureToImage(AndroidImageHelpers.android.kt:97)
at com.example.myapp.util.ScreenshotComparatorKt.assertScreenshotMatchesGolden(ScreenshotComparator.kt:43)
at com.example.myapp.ui.onboarding.RichTextNodeComposerTest.headingsAreComposed(RichTextNodeComposerTest.kt:37)
... 42 trimmed
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.test.platform.graphics.HardwareRendererCompat" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/com.example.myapp.internal.test-mYxqQihs-GuTV6BiCAfRJw==/base.apk", zip file "/data/app/com.example.myapp.internal-KAY2OSfzc7r1bXt_h1NwVA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.myapp.internal.test-mYxqQihs-GuTV6BiCAfRJw==/lib/x86, /data/app/com.example.myapp.internal-KAY2OSfzc7r1bXt_h1NwVA==/lib/x86, /system/lib, /vendor/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 48 more
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bentrengrove** [comment]
Hi! 

This issue seems unrelated to the `compose-samples` repository directly, issues here are reserved for bug reports within the `compose-samples` apps or feature requests for the sample apps. 

For questions related to Jetpack Compose - we recommend asking them on [StackOverflow](https://stackoverflow.com/questions/ask?tags=android-jetpack-compose) with the `android-jetpack-compose` tag. 

If you find an issue with an Android Jetpack Compose components, report it using the [Jetpack Compose issue tracker](https://issuetracker.google.com/issues/new?component=612128&template=1253476).
